language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: Ujy8ogsN6A0R7rADVbEhF5/NkPnIqqAVBM5d0O7iBc1xWzenlHu0Pm1rdin73iKFfoZ1vMhafn26LswYzyZE3kvNj5GVMYbAeFHUrqafYzTKioVjRE/NuPdGZbLYceiVf/mMghGZeJtM+y8xec+CNt2pyFKkpA+ASPKDZ1UqflY=
before_script:
- chmod +x ./deploy.sh
after_success:
- ./deploy.sh
