language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  api-key: GITHUB OAUTH TOKEN
  file: target/beancp-0.1.jar
  on:
    repo: erchu/bean-cp
env:
  global:
  - secure: DK9tv6x8LLJo7XxhOPLPqX/qdpdkgyz2ixa6wV4bNZX3Gm7OkMLldRKYOpjm0fnhqVgNPNzE31MwVb12RL8CokVNNOv8vPXI8jdG68/tLNrOx2Dq3qGl5ivkFkYnI3WaI3A5NUbCMYaxYO1qOZrAvhJfIH5LWDZnRa3WQEpj9io=
