language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: UnJ1PQ3oFGS3rNJsDGXZe4MYlWB7OBaOQOZXb0a1b0b3Y2yvMzMLhV5I55FYXAlU1Y72n7/SyifUnFoi3Z50XhOPTG+FxykW8RqwlQ+XSekSb9ALB62eWYHObwgVQEP1TT52FBp25JNb/OYMUb/zzY/MlHYZpqKV6Jv0ckFwSo8=
  file: target/beancp-0.1.jar
  on:
    repo: erchu/bean-cp
